import { SupabaseClient } from '@supabase/supabase-js';
import { Database } from '../../types/database.types';
import { PMEvaluationResult, PMScheduleModel, PMVehicleSubscription } from './pmTypes';
import { PMEngine } from './pmEngine';
import { logger } from '../../lib/logger';

export class PMWorkOrderGenerator {
  /**
   * Attempts to generate a Work Order based on a PM evaluation result.
   * Leverages the pm_evaluation_events table for idempotency.
   */
  public static async generatePreventiveWorkOrder(
    supabase: SupabaseClient<Database>,
    tenantId: string,
    vehicleId: string,
    vehiclePlate: string,
    subscription: PMVehicleSubscription,
    schedule: PMScheduleModel,
    result: PMEvaluationResult
  ): Promise<{ success: boolean; workOrderId?: string; skippedReason?: string }> {
    
    // 1. Check eligibility
    if (!result.is_eligible_for_wo) {
      return { success: false, skippedReason: 'Not eligible for Work Order' };
    }

    const triggerKey = PMEngine.generateTriggerKey(subscription.id, result);

    // 2. Insert into pm_evaluation_events (IDEMPOTENCY CHECK)
    const { data: eventData, error: eventError } = await supabase
      .from('pm_evaluation_events')
      .insert({
        tenant_id: tenantId,
        pm_subscription_id: subscription.id,
        trigger_key: triggerKey.cycleIdentifier
      })
      .select('id')
      .single();

    if (eventError) {
      if (eventError.code === '23505' || eventError.message?.includes('duplicate key')) {
        return { success: false, skippedReason: 'Idempotency key already exists. Work Order already generated for this cycle.' };
      }
      throw eventError;
    }

    const eventId = eventData.id;

    // 3. Prepare Work Order Payload
    const workOrderPayload = {
      tenant_id: tenantId,
      vehicle_id: vehicleId,
      vehicle_plate: vehiclePlate,
      type: 'Preventive',
      status: 'Open',
      labor_hours: schedule.estimated_labor_hours || 0,
      hourly_rate: 85.00, // Default or fetch from settings
      labor_cost: (schedule.estimated_labor_hours || 0) * 85.00,
      parts_used: schedule.required_parts || [],
      before_notes: `Automatically generated by PM Engine.\nSchedule: ${schedule.title}\nResolved Rule: ${subscription.resolved_rule_id || 'Fallback'}\nTrigger: ${result.trigger_type} at ${result.current_value} (Threshold: ${result.threshold_value})`,
      
      // PM Provenance
      pm_schedule_id: schedule.id,
      pm_subscription_id: subscription.id,
      pm_trigger_type: result.trigger_type,
      pm_trigger_value: String(result.threshold_value)
    };

    // 4. Insert Work Order
    const { data: woData, error: woError } = await supabase
      .from('work_orders')
      .insert(workOrderPayload)
      .select('id')
      .single();

    if (woError) {
      // Rollback the idempotency event if the WO creation failed
      await supabase.from('pm_evaluation_events').delete().eq('id', eventId);
      throw woError;
    }

    // 5. Update the idempotency event with the created Work Order ID
    await supabase
      .from('pm_evaluation_events')
      .update({ work_order_id: woData.id })
      .eq('id', eventId);

    // 6. Update the subscription's next_due targets for the next cycle
    await this.rollForwardSubscription(supabase, subscription, result);

    return { success: true, workOrderId: woData.id };
  }

  /**
   * Advances the subscription's next_due targets after generating a Work Order.
   * STRICTLY uses resolved_* snapshot data for correctness.
   */
  private static async rollForwardSubscription(
    supabase: SupabaseClient<Database>,
    subscription: PMVehicleSubscription,
    result: PMEvaluationResult
  ) {
    if (!subscription.resolved_trigger_type || !subscription.resolved_interval_value) {
      logger.error({ subscriptionId: subscription.id }, 'Missing resolved data for roll-forward');
      throw new Error(`Cannot roll forward subscription ${subscription.id} - missing resolved metadata`);
    }

    const updates: Partial<PMVehicleSubscription> = {};
    const interval = Number(subscription.resolved_interval_value);

    // Use resolved_trigger_type, not schedule.trigger_type!
    if (subscription.resolved_trigger_type === 'ODOMETER') {
      updates.last_service_odometer = Number(result.threshold_value);
      updates.next_due_odometer = Number(result.threshold_value) + interval;
    } else if (subscription.resolved_trigger_type === 'ENGINE_HOURS') {
      updates.last_service_engine_hours = Number(result.threshold_value);
      updates.next_due_engine_hours = Number(result.threshold_value) + interval;
    } else if (subscription.resolved_trigger_type === 'TIME') {
      const currentTarget = new Date(String(result.threshold_value));
      updates.last_service_date = currentTarget.toISOString();
      
      const nextTarget = new Date(currentTarget);
      
      // Default to DAYS if no unit specified in resolved snapshot
      const unit = subscription.resolved_interval_unit || 'DAYS';
      
      if (unit === 'MONTHS') {
        nextTarget.setMonth(nextTarget.getMonth() + interval);
      } else {
        nextTarget.setDate(nextTarget.getDate() + interval);
      }
      updates.next_due_date = nextTarget.toISOString();
    }

    const { error } = await supabase
      .from('pm_vehicle_subscriptions')
      .update(updates)
      .eq('id', subscription.id);
      
    if (error) {
      throw new Error(`Failed to roll forward subscription ${subscription.id}: ${error.message}`);
    }
  }
}
